# Generated by Django 2.2.16 on 2020-10-31 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room_Clima',
            new_name='Room_Climate',
        ),
    ]
