# Generated by Django 2.2.16 on 2020-10-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0002_auto_20201031_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_climate',
            name='time',
            field=models.DateTimeField(verbose_name='Time'),
        ),
    ]
