# Generated by Django 2.2.16 on 2020-10-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_auto_20201031_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_climate',
            name='humidity',
            field=models.FloatField(blank=True, verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='room_climate',
            name='temperature',
            field=models.FloatField(blank=True, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='room_climate',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time'),
        ),
    ]
