# Generated by Django 2.2.16 on 2020-11-02 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0007_auto_20201102_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_climate',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='time'),
        ),
    ]
