# Generated by Django 3.1.2 on 2020-11-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0009_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_name', models.CharField(max_length=100)),
                ('share_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpersonvehicle',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpersonvehicle',
            name='person',
        ),
        migrations.RemoveField(
            model_name='historicalpersonvehicle',
            name='vehicle',
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='personvehicle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='personvehicle',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personvehicle',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='HistoricalPerson',
        ),
        migrations.DeleteModel(
            name='HistoricalPersonVehicle',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonVehicle',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
