# Generated by Django 3.1.2 on 2020-11-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0010_auto_20201120_1254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shares',
            new_name='Share',
        ),
    ]
