# Generated by Django 3.1.2 on 2020-11-20 13:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0011_auto_20201120_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share_Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_of_purchase', models.DateTimeField(default=datetime.datetime.now, verbose_name='time')),
                ('prize', models.FloatField(blank=True, null=True, verbose_name='prize')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='number')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='number')),
                ('expenses', models.FloatField(blank=True, null=True, verbose_name='number')),
                ('share_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dev.share')),
            ],
        ),
    ]
